# Generated by Django 5.2.9 on 2026-01-05 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0008_alter_article_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
