# Generated by Django 5.2.9 on 2026-01-05 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0010_remove_article_order_article_deleted_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='article',
            name='is_deleted',
        ),
    ]
