# Generated by Django 5.2.9 on 2026-01-08 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0012_article_deleted_at_article_is_deleted'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['position']},
        ),
        migrations.AddField(
            model_name='article',
            name='position',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
