# Generated by Django 5.2.9 on 2026-01-13 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0013_alter_article_options_article_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='is_homepage',
            field=models.BooleanField(default=False),
        ),
    ]
