# Generated by Django 5.2.9 on 2026-01-13 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0014_article_is_homepage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='homepage',
        ),
    ]
