# Generated by Django 5.2.9 on 2026-01-13 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0015_remove_article_homepage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='is_homepage',
            new_name='homepage',
        ),
    ]
