# Generated by Django 5.2.9 on 2026-01-16 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mediamgmt', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='media',
            name='mime_type',
        ),
        migrations.RemoveField(
            model_name='media',
            name='size',
        ),
        migrations.AlterField(
            model_name='media',
            name='caption',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='media',
            name='file',
            field=models.FileField(upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='media',
            name='order',
            field=models.IntegerField(default=0),
        ),
    ]
