# Generated by Django 5.2.9 on 2026-01-16 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mediamgmt', '0003_alter_media_options_remove_media_order_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='media',
            options={'ordering': ['position', '-created_at']},
        ),
        migrations.RemoveField(
            model_name='media',
            name='alt_text',
        ),
        migrations.RemoveField(
            model_name='media',
            name='caption',
        ),
        migrations.AddField(
            model_name='media',
            name='media_type',
            field=models.CharField(choices=[('image', 'Image'), ('video', 'Video')], default='image', max_length=10),
        ),
        migrations.AlterField(
            model_name='media',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
