# Generated by Django 5.2.9 on 2026-01-18 04:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mediamgmt', '0005_alter_media_options_rename_position_media_sort_order_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='media',
            options={'ordering': ['order', '-created_at']},
        ),
        migrations.RenameField(
            model_name='media',
            old_name='sort_order',
            new_name='order',
        ),
        migrations.RenameField(
            model_name='media',
            old_name='is_active',
            new_name='status',
        ),
        migrations.RemoveField(
            model_name='media',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='media',
            name='updated_at',
        ),
    ]
