# Generated by Django 5.2.9 on 2026-01-18 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mediamgmt', '0006_alter_media_options_rename_sort_order_media_order_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='media',
            options={'ordering': ['sort_order', '-created_at']},
        ),
        migrations.RenameField(
            model_name='media',
            old_name='status',
            new_name='is_active',
        ),
        migrations.RenameField(
            model_name='media',
            old_name='order',
            new_name='sort_order',
        ),
        migrations.AddField(
            model_name='media',
            name='alt_text',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='media',
            name='caption',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='media',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='media',
            name='media_type',
            field=models.CharField(choices=[('image', 'Image'), ('video', 'Video')], default='image', max_length=10),
        ),
    ]
