# Generated by Django 5.2.9 on 2026-01-18 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mediamgmt', '0007_alter_media_options_rename_status_media_is_active_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='media',
            options={},
        ),
        migrations.AddField(
            model_name='media',
            name='video_source',
            field=models.CharField(blank=True, choices=[('local', 'Local File'), ('youtube', 'YouTube Link')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='media',
            name='youtube_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='media',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='media/'),
        ),
    ]
