# Generated by Django 5.2.9 on 2026-01-18 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mediamgmt', '0008_alter_media_options_media_video_source_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='media',
            options={'ordering': ['sort_order', '-created_at']},
        ),
        migrations.RemoveField(
            model_name='media',
            name='video_source',
        ),
        migrations.RemoveField(
            model_name='media',
            name='youtube_link',
        ),
        migrations.AlterField(
            model_name='media',
            name='file',
            field=models.FileField(upload_to='media/'),
        ),
    ]
