# Generated by Django 5.2.9 on 2026-01-18 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mediamgmt', '0009_alter_media_options_remove_media_video_source_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='video_source',
            field=models.CharField(choices=[('local', 'Local Video'), ('youtube', 'YouTube')], default='local', max_length=10),
        ),
        migrations.AddField(
            model_name='media',
            name='youtube_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
