# Generated by Django 5.2.9 on 2026-01-18 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mediamgmt', '0010_media_video_source_media_youtube_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='media',
            name='media_type',
            field=models.CharField(choices=[('image', 'Image'), ('video', 'Video')], max_length=10),
        ),
        migrations.AlterField(
            model_name='media',
            name='video_source',
            field=models.CharField(blank=True, choices=[('local', 'Local Video'), ('youtube', 'YouTube')], max_length=10, null=True),
        ),
    ]
