# Generated by Django 5.2.9 on 2026-01-19 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mediamgmt', '0011_alter_media_file_alter_media_media_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='media_type',
            field=models.CharField(choices=[('image', 'Image'), ('video', 'Video')], default='image', max_length=10),
        ),
        migrations.AlterField(
            model_name='media',
            name='video_source',
            field=models.CharField(choices=[('local', 'Local Video'), ('youtube', 'YouTube')], default='local', max_length=10),
        ),
    ]
