# Generated by Django 5.2.9 on 2026-01-25 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contentmgmt', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediafile',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
