# Generated by Django 5.2.9 on 2026-01-25 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contentmgmt', '0002_mediafile_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mediafile',
            name='updated_at',
        ),
    ]
