# Generated by Django 5.2.9 on 2026-01-26 05:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contentmgmt', '0004_alter_folder_parent_alter_mediafile_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='folder',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subfolders', to='contentmgmt.folder'),
        ),
        migrations.AlterField(
            model_name='mediafile',
            name='file',
            field=models.FileField(upload_to='media_files/%Y/%m/%d/'),
        ),
    ]
